franka_teleoperation_controller:
    type: franka_controllers/FrankaTeleoperationController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

franka_cartesian_impedance_controller:
    type: franka_controllers/FrankaCartesianImpedanceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7

franka_cartesian_pose_controller:
    type: franka_controllers/FrankaCartesianPoseController
    arm_id: panda

franka_force_controller:
    type: franka_controllers/FrankaForceController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
